GET http://localhost:8080/v1/prot
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFzZDEyMzU1NDM1ZGZzNTMifQ.eyJ1cm46ZXhhbXBsZTpjbGFpbSI6dHJ1ZX0.ESw3sNgC9vDDUvYn040SVudU6aww3J7J-DjlF9qoLf9WqBGNRTtIqdQkwKbTPpxdl8tO9UY3jJMug853SgYHWjN-5OxraqrClzSCjIl5xATun_21B6Ep1b0dQK-alEuHJM-X-pHYgWe8fjF4JNA2SlNyA0VrT24NE5tUytki30_S205G0du4gL7ZRo9o5LWGL-hNAoPbBGhUd18Y5-n4YGx_AM6cxiuINh75eN374rEo16cf4NdVaAaimcqpOG1Zwf-YULPfmunaaH9QeKm0wosO0m9W_0EHYdw_e-jh7B5nWltWlAd-Nxb71KcHMxGOoD4z0GPJZlEEtQNetMnSrQ