GET http://localhost:8080/v1/prot
Authorization: Bearer eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImFzZDEyMzU1NDM1ZGZzNTMifQ.eyJ1cm46ZXhhbXBsZTpjbGFpbSI6dHJ1ZX0.1CHHn0QOl6Vl7_16JtkGcY7G0le2TCFLANWTEqqietLsshI_-wmQOZ1zOsaWd4p2AQxEeEZUdQxBQl5_XBWdf5fu59P69sZ-yXXKZQT6oO3z6auVdO26Nalc0xgKiRnMOWqXceaQXqg8IFlz7Ho4zqGYUMrFtmADNACk62yo1cRLkht6QyhEYRulKe14QFQRILASUzCoY3y-bbF-RaTmFOQBOB3XUKhPUXjN7ZJDqcGf-DkFbX-xcPxE7HaguEU9KrS4femVIJ6oAFHMllJRU-RfY9jWx44Kw0HRFzcU0eU4sc0oFE4jOskINLI2r36TTv1O5MsVMxVG9IFQ_Aqqlw